Repository tiangolo/latest-changes, pull requests merged in 2023-11, with the labels that each got.

#50 👷 Update CI, Dependabot, funding
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/latest-changes.yml
Labels: internal

#39 ✏️ Fix typo in syntax for using the GitHub Action tag directly (instead of with Docker) in README
  README.md
Labels: docs

#57 🐛 Fix handling multiple section headers
  README.md
  latest_changes/main.py
  tests/test_generate_content.py
Labels: bug

#59 🐛 Detect if there's a second level header after the release content, to support the first change in a README with a last section for a license
  README.md
  action.yml
  latest_changes/main.py
  tests/test_generate_content.py
Labels: bug
